(function(){
  if(window.__campaignHeaderReady)return;window.__campaignHeaderReady=true;
  const pages=[['voters','Residents'],['assign','Assign'],['call','Calls'],['vote','Votes'],['d2d','Visits'],['transport','Transport'],['ai-dashboard','Insights']];
  const qs=()=>new URLSearchParams(location.search);
  const party=()=>qs().get('party')||sessionStorage.getItem('campaignParty')||'PNC';
  const current=()=>location.pathname.split('/').pop().replace('.html','')||'index';
  const href=p=>p+'.html?party='+encodeURIComponent(party())+'&v=clean1';
  function css(){if(document.getElementById('campaignHeaderCss'))return;const s=document.createElement('style');s.id='campaignHeaderCss';s.textContent='.topbar,.campaign-header{position:sticky!important;top:0!important;z-index:1000!important;min-height:64px!important;padding:0 18px!important;background:#fff!important;border-bottom:1px solid #dbe4f0!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:14px!important;width:100%!important;box-sizing:border-box!important}.brand,.campaign-brand{display:flex!important;align-items:center!important;gap:10px!important;font-size:16px!important;font-weight:950!important;color:#0f172a!important;text-decoration:none!important;white-space:nowrap!important}.brand-icon{width:32px!important;height:32px!important;display:grid!important;place-items:center!important;border-radius:12px!important;background:#eff6ff!important}.toolbar,.nav,.campaign-nav{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;overflow-x:auto!important;scrollbar-width:none!important}.toolbar::-webkit-scrollbar,.nav::-webkit-scrollbar,.campaign-nav::-webkit-scrollbar{display:none!important}.topbar .btn,.campaign-nav .btn,.toolbar .btn,.nav .btn{height:44px!important;min-height:44px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;border:1px solid #dbe4f0!important;border-radius:12px!important;background:#fff!important;color:#1f3b66!important;padding:0 14px!important;font-size:14px!important;font-weight:950!important;text-decoration:none!important;white-space:nowrap!important}.topbar .btn.dark,.topbar .btn.active,.campaign-nav .btn.active{background:#1f3b66!important;color:#fff!important;border-color:#1f3b66!important}#logoutBtn,.logout-link{background:#0f172a!important;color:#fff!important;border-color:#0f172a!important}#campaignGlobalStatus,.app-header-stats{display:none!important}@media(max-width:900px){.topbar,.campaign-header{height:auto!important;align-items:flex-start!important;flex-direction:column!important;padding:10px 12px!important}.toolbar,.nav,.campaign-nav{max-width:100%!important;width:100%!important;justify-content:flex-start!important}.topbar .btn,.toolbar .btn,.nav .btn,.campaign-nav .btn{height:44px!important;min-height:44px!important;font-size:13px!important;padding:0 12px!important}}';document.head.appendChild(s)}
  function build(){css();const header=document.querySelector('header.topbar,header.campaign-header');if(!header)return;header.classList.add('campaign-header');let brand=header.querySelector('.brand,.campaign-brand');if(!brand){brand=document.createElement('a');header.prepend(brand)}brand.className='brand campaign-brand';brand.href='index.html?v=clean1';brand.innerHTML='<span class="brand-icon">&#128499;</span><span>Villimale Campaign</span>';let nav=header.querySelector('.toolbar,.nav,.campaign-nav');if(!nav){nav=document.createElement('nav');header.appendChild(nav)}nav.className='campaign-nav';const cur=current();nav.innerHTML=pages.map(([p,l])=>'<a class="btn '+(cur===p?'active':'')+'" href="'+href(p)+'" data-party-link="'+p+'">'+l+'</a>').join('')+'<a id="logoutBtn" class="btn dark logout-link" href="login.html?v=clean1">Logout</a>'}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();window.addEventListener('load',build,{once:true});[300,900,1800].forEach(t=>setTimeout(build,t));
})();