(function(){
  if(window.__campaignHeaderReady)return;window.__campaignHeaderReady=true;
  const pages=[['voters','Voters'],['assign','Assign'],['call','Call Center'],['vote','Vote'],['d2d','D2D'],['transport','Transport'],['ai-dashboard','AI Dashboard']];
  function party(){return new URLSearchParams(location.search).get('party')||'PNC'}
  function current(){const p=location.pathname.split('/').pop().replace('.html','')||'voters';return p==='index'?'voters':p}
  function href(page){return page+'.html?party='+encodeURIComponent(party())}
  function css(){if(document.getElementById('campaignHeaderCss'))return;const s=document.createElement('style');s.id='campaignHeaderCss';s.textContent=`
    .topbar,.campaign-header{position:sticky!important;top:0!important;z-index:1000!important;min-height:64px!important;height:64px!important;padding:0 18px!important;background:#fff!important;border-bottom:1px solid #dbe4f0!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:14px!important;box-shadow:none!important;width:100%!important;box-sizing:border-box!important;overflow:visible!important}
    .brand,.campaign-brand{display:flex!important;align-items:center!important;gap:10px!important;min-width:max-content!important;color:#0f172a!important;text-decoration:none!important;font-size:16px!important;line-height:1!important;font-weight:950!important;letter-spacing:-.02em!important;white-space:nowrap!important;margin:0!important;padding:0!important}
    .brand-mark{width:30px!important;height:30px!important;border-radius:10px!important;display:inline-flex!important;background:linear-gradient(135deg,#2563eb,#14b8a6)!important;flex:0 0 auto!important}
    .toolbar,.nav,.campaign-nav{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;flex-wrap:nowrap!important;margin:0!important;padding:0!important;min-height:40px!important;overflow-x:auto!important;max-width:calc(100vw - 310px)!important;scrollbar-width:none!important}
    .toolbar::-webkit-scrollbar,.nav::-webkit-scrollbar,.campaign-nav::-webkit-scrollbar{display:none!important}
    .topbar .btn,.campaign-nav .btn,.toolbar .btn,.nav .btn{height:40px!important;min-height:40px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;border:1px solid #dbe4f0!important;border-radius:12px!important;background:#fff!important;color:#1f3b66!important;padding:0 14px!important;font-size:14px!important;font-weight:950!important;line-height:1!important;text-decoration:none!important;white-space:nowrap!important;box-shadow:none!important;cursor:pointer!important;margin:0!important}
    .topbar .btn.dark,.topbar .btn.active,.campaign-nav .btn.dark,.campaign-nav .btn.active,.toolbar .btn.dark,.toolbar .btn.active,.nav .btn.dark,.nav .btn.active{background:#1f3b66!important;color:#fff!important;border-color:#1f3b66!important}
    #logoutBtn{height:40px!important;min-height:40px!important;background:#0f172a!important;color:#fff!important;border-color:#0f172a!important}
    @media(max-width:900px){.topbar,.campaign-header{height:auto!important;min-height:64px!important;align-items:flex-start!important;flex-direction:column!important;padding:10px 12px!important}.toolbar,.nav,.campaign-nav{max-width:100%!important;width:100%!important;justify-content:flex-start!important}.brand,.campaign-brand{height:38px!important}.topbar .btn,.toolbar .btn,.nav .btn,.campaign-nav .btn{height:38px!important;min-height:38px!important;font-size:13px!important;padding:0 12px!important}}
  `;document.head.appendChild(s)}
  function fixText(){document.querySelectorAll('.stat span,.status-pill,.eyebrow,.status,.status-message,.muted').forEach(el=>{let t=el.textContent;t=t.replace(/\bVISIBLE\b/g,'VOTERS').replace(/\bVisible\b/g,'Voters').replace(/\bUpdated\s+(\d{1,2}:\d{2}\s*[AP]M)\b/i,'Updated: $1');if(t!==el.textContent)el.textContent=t})}
  function build(){css();const old=document.querySelector('header.topbar,header.campaign-header');if(!old)return;old.classList.add('campaign-header');let brand=old.querySelector('.brand,.campaign-brand');if(!brand){brand=document.createElement('a');brand.href=href('voters');brand.className='brand campaign-brand';brand.textContent='Villimale Campaign Manager';old.prepend(brand)}brand.classList.add('campaign-brand');brand.href=href('voters');let nav=old.querySelector('.toolbar,.nav,.campaign-nav');if(!nav){nav=document.createElement('nav');old.appendChild(nav)}nav.className='campaign-nav';const cur=current();nav.innerHTML=pages.map(([p,l])=>`<a id="${p.replace('-','')}Link" class="btn ${cur===p?'active':''}" href="${href(p)}" data-party-link="${p}">${l}</a>`).join('');if(cur==='voters'){const b=document.createElement('button');b.id='logoutBtn';b.className='btn dark';b.type='button';b.textContent='Logout';nav.appendChild(b);setTimeout(()=>{if(typeof window.setupLogout==='function')window.setupLogout()},0)}fixText()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
  window.addEventListener('load',build,{once:true});setTimeout(build,300);setTimeout(build,1000);
})();