(function(){
  if(window.__campaignHeaderReady)return;window.__campaignHeaderReady=true;
  const pages=[['voters','Voters'],['assign','Assign'],['call','Call Center'],['vote','Vote'],['d2d','D2D'],['transport','Transport'],['ai-dashboard','AI Dashboard']];
  const qs=()=>new URLSearchParams(location.search);
  const party=()=>qs().get('party')||'PNC';
  const current=()=>{const p=location.pathname.split('/').pop().replace('.html','')||'voters';return p==='index'?'voters':p};
  const href=p=>p+'.html?party='+encodeURIComponent(party());
  function css(){if(document.getElementById('campaignHeaderCss'))return;const s=document.createElement('style');s.id='campaignHeaderCss';s.textContent='.topbar,.campaign-header{position:sticky!important;top:0!important;z-index:1000!important;min-height:64px!important;height:64px!important;padding:0 18px!important;background:#fff!important;border-bottom:1px solid #dbe4f0!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:14px!important;width:100%!important;box-sizing:border-box!important}.brand,.campaign-brand{font-size:16px!important;font-weight:950!important;color:#0f172a!important;text-decoration:none!important;white-space:nowrap!important}.toolbar,.nav,.campaign-nav{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;overflow-x:auto!important;max-width:calc(100vw - 310px)!important;scrollbar-width:none!important}.toolbar::-webkit-scrollbar,.nav::-webkit-scrollbar,.campaign-nav::-webkit-scrollbar{display:none!important}.topbar .btn,.campaign-nav .btn,.toolbar .btn,.nav .btn{height:40px!important;min-height:40px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;border:1px solid #dbe4f0!important;border-radius:12px!important;background:#fff!important;color:#1f3b66!important;padding:0 14px!important;font-size:14px!important;font-weight:950!important;text-decoration:none!important;white-space:nowrap!important}.topbar .btn.dark,.topbar .btn.active,.campaign-nav .btn.active{background:#1f3b66!important;color:#fff!important;border-color:#1f3b66!important}#logoutBtn{background:#0f172a!important;color:#fff!important;border-color:#0f172a!important}@media(max-width:900px){.topbar,.campaign-header{height:auto!important;align-items:flex-start!important;flex-direction:column!important;padding:10px 12px!important}.toolbar,.nav,.campaign-nav{max-width:100%!important;width:100%!important;justify-content:flex-start!important}.topbar .btn,.toolbar .btn,.nav .btn,.campaign-nav .btn{height:38px!important;min-height:38px!important;font-size:13px!important;padding:0 12px!important}}';document.head.appendChild(s)}
  function loadGlobal(){if(window.__campaignGlobalStatusLoading)return;window.__campaignGlobalStatusLoading=true;const s=document.createElement('script');s.src='js/campaign-global-status.js?v=20260708-1';document.head.appendChild(s)}
  function build(){css();const header=document.querySelector('header.topbar,header.campaign-header');if(!header)return;header.classList.add('campaign-header');let brand=header.querySelector('.brand,.campaign-brand');if(!brand){brand=document.createElement('a');header.prepend(brand)}brand.className='brand campaign-brand';brand.href=href('voters');brand.textContent='Villimale Campaign Manager';let nav=header.querySelector('.toolbar,.nav,.campaign-nav');if(!nav){nav=document.createElement('nav');header.appendChild(nav)}nav.className='campaign-nav';const cur=current();nav.innerHTML=pages.map(([p,l])=>'<a class="btn '+(cur===p?'active':'')+'" href="'+href(p)+'" data-party-link="'+p+'">'+l+'</a>').join('');if(cur==='voters'){const b=document.createElement('button');b.id='logoutBtn';b.className='btn dark';b.type='button';b.textContent='Logout';nav.appendChild(b)}loadGlobal()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();window.addEventListener('load',build,{once:true});setTimeout(build,500);
})();