(function(){
  const page=document.body?.dataset?.workspacePage;
  if(!page)return;
  const config={
    call:{title:'Call Center',subtitle:'Call voters, update phone/reach/vote result, and write remarks.',focusField:'phone_status',statuses:[['need-call','Need Call'],['called','Called'],['wrong-number','Wrong Number'],['out-of-range','Out of Range'],['no-phone','No Phone']],defaultFilter:'need-call'},
    vote:{title:'Vote Result',subtitle:'Track confirmed Will Vote, Not Vote, and Pending voters.',focusField:'vote_status',statuses:[['pending','Pending'],['will-vote','Will Vote'],['no-vote','Not Vote']],defaultFilter:'pending'},
    d2d:{title:'Door To Door',subtitle:'Track house visits, reached voters, follow-up, and pending door-to-door work.',focusField:'d2d_status',statuses:[['pending','Pending'],['visited','Visited'],['follow-up','Follow-up'],['not-home','Not Home']],defaultFilter:'pending'},
    transport:{title:'Transportation',subtitle:'Track voters who need transport and update transport status.',focusField:'transport_status',statuses:[['none','No Transport'],['need-transport','Need Transport'],['arranged','Arranged'],['completed','Completed']],defaultFilter:'need-transport'}
  }[page];
  if(!config)return;
  let rows=[],client=null,selectedId=null;
  const $=id=>document.getElementById(id);const clean=v=>String(v||'').trim();const low=v=>clean(v).toLowerCase();const num=v=>new Intl.NumberFormat('en-US').format(v||0);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const party=()=>new URLSearchParams(location.search).get('party')||'PNC';
  function getClient(){if(client)return client;const c=window.APP_CONFIG;if(!window.supabase||!c)return null;client=window.supabase.createClient(c.supabaseUrl,c.supabaseKey);return client}
  function labelOf(value,field){if(field==='reach_status')return value==='reached'?'Reached':'Not Reached';const item=(config.statuses||[]).find(s=>s[0]===value);return item?item[1]:(clean(value)||'Pending')}
  function val(row,field){return clean(row[field]||'').toLowerCase()||((field==='transport_status')?'none':'pending')}
  function result(row){const vs=val(row,'vote_status');if(vs==='will-vote')return['will','Will Vote'];if(['no-vote','not-vote'].includes(vs))return['no','Not Vote'];return['pending','Pending']}
  function isAssigned(row){const a=low(row.vote_assigned_by);return !!a&&a!=='naappe@gmail.com'}
  function uniqueHouses(list){return new Set(list.map(r=>low(r.house||'No house')).filter(Boolean)).size}
  function initials(n){return clean(n).split(/\s+/).slice(0,2).map(p=>p[0]||'').join('').toUpperCase()||'?'}
  function photo(r){return r.photo_url?`<img src="${esc(r.photo_url)}" alt="${esc(r.name)}">`:esc(initials(r.name))}
  function setUrlFilter(status){const url=new URL(location.href);if(status)url.searchParams.set('status',status);else url.searchParams.delete('status');history.replaceState(null,'',url)}
  function pageLink(target,status){const url=new URL(target+'.html',location.href);url.searchParams.set('party',party());if(status)url.searchParams.set('status',status);return url.pathname.split('/').pop()+url.search}
  async function load(){const sb=getClient(),c=window.APP_CONFIG;if(!sb||!c)throw new Error('Supabase not ready');let out=[],from=0,size=1000;while(true){let q=sb.from(c.table).select('id,image_number,photo_url,name,national_id,house,lives_in,phone,party,election_box,phone_status,reach_status,vote_status,transport_status,d2d_status,remarks,vote_assigned_by').order('image_number',{ascending:true}).range(from,from+size-1);const p=party().toUpperCase();if(p!=='ALL')q=q.eq('party',p);const {data,error}=await q;if(error)throw error;out.push(...(data||[]));if(!data||data.length<size)break;from+=size}rows=out;buildOptions();render()}
  function buildOptions(){const status=$('statusSelect');const fromUrl=new URLSearchParams(location.search).get('status');status.innerHTML='<option value="">All statuses</option>'+config.statuses.map(s=>`<option value="${esc(s[0])}">${esc(s[1])}</option>`).join('');status.value=fromUrl||config.defaultFilter||'';const houses=[...new Set(rows.map(r=>clean(r.house)||'No house'))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));$('houseSelect').innerHTML='<option value="">All houses</option>'+houses.map(h=>`<option value="${esc(low(h))}">${esc(h)}</option>`).join('')}
  function filtered(){const s=low($('searchInput').value),st=$('statusSelect').value,h=$('houseSelect').value;return rows.filter(r=>{if(st&&val(r,config.focusField)!==st)return false;if(h&&low(r.house||'No house')!==h)return false;if(page==='call'&&st==='need-call'&&low(r.phone_status)==='no-phone')return false;if(!s)return true;return [r.name,r.national_id,r.house,r.lives_in,r.phone,r.party,r.remarks,r.vote_assigned_by].some(v=>low(v).includes(s))})}
  function setStatLabels(){const cards=document.querySelectorAll('.stat span');if(cards[0])cards[0].textContent='Voters';if(cards[1])cards[1].textContent='Houses';if(cards[2])cards[2].textContent=config.statuses.find(s=>s[0]===config.defaultFilter)?.[1]||'Work';if(cards[3])cards[3].textContent='Will Vote';if(cards[4])cards[4].textContent='Assigned'}
  function stats(){const list=filtered();const allWork=rows.filter(r=>val(r,config.focusField)===config.defaultFilter);$('sTotal').textContent=num(list.length);$('sShowing').textContent=num(uniqueHouses(list));$('sMain').textContent=num(allWork.length);$('sWill').textContent=num(rows.filter(r=>val(r,'vote_status')==='will-vote').length);$('sPending').textContent=num(rows.filter(isAssigned).length);$('status').textContent=`Showing ${num(list.length)} voters in ${num(uniqueHouses(list))} houses. Click a card to update here.`;return list}
  function setupStatLinks(){const cards=document.querySelectorAll('.stat');if(cards[0])cards[0].onclick=()=>{location.href=pageLink('voters')};if(cards[1])cards[1].onclick=()=>{$('statusSelect').value='';setUrlFilter('');render()};if(cards[2])cards[2].onclick=()=>{$('statusSelect').value=config.defaultFilter||'';setUrlFilter(config.defaultFilter||'');render()};if(cards[3])cards[3].onclick=()=>{location.href=pageLink('vote','will-vote')};if(cards[4])cards[4].onclick=()=>{location.href=pageLink('assign')};cards.forEach(c=>{c.tabIndex=0;c.title='Click to open/filter';c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();c.click()}})})}
  function group(list){const map=new Map();list.forEach(r=>{const h=clean(r.house)||'No house';if(!map.has(h))map.set(h,[]);map.get(h).push(r)});return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}))}
  function card(r){const [cls,res]=result(r);return`<article class="card" data-row-id="${esc(r.id)}"><div class="photo">${photo(r)}</div><div><div class="name">${esc(r.name||'Unknown voter')}</div><div class="meta">ID: ${esc(r.national_id||'-')}<br>House: ${esc(r.house||'-')}<br>Phone: ${esc(r.phone||'No phone')}<br>Box: ${esc(r.election_box||'-')}</div><div class="badges"><span class="badge ${esc(cls)}">${esc(res)}</span><span class="badge neutral">${esc(labelOf(val(r,config.focusField),config.focusField))}</span></div><span class="open-note">Click Card / Update</span></div></article>`}
  function render(){setUrlFilter($('statusSelect')?.value||'');const list=stats();$('list').innerHTML=list.length?group(list).map(([h,items])=>`<div class="house">${esc(h)} · ${num(items.length)} voters</div><div class="grid">${items.map(card).join('')}</div>`).join(''):'<div class="empty">No voters match this filter.</div>'}
  function open(row){selectedId=row.id;$('modalTitle').textContent=row.name||'Update voter';$('modalMeta').textContent=`${row.house||'-'} · ${row.phone||'No phone'}`;$('phoneStatus').value=val(row,'phone_status');$('reachStatus').value=val(row,'reach_status')||'not-reached';$('voteStatus').value=val(row,'vote_status')||'pending';$('d2dStatus').value=val(row,'d2d_status')||'pending';$('transportStatus').value=val(row,'transport_status')||'none';$('remarks').value=row.remarks||'';$('modal').hidden=false}
  function close(){$('modal').hidden=true;selectedId=null}
  function rowById(id){return rows.find(r=>String(r.id)===String(id))}
  async function save(e){e.preventDefault();const row=rowById(selectedId),sb=getClient(),c=window.APP_CONFIG;if(!row||!sb||!c)return;const updates={phone_status:$('phoneStatus').value,reach_status:$('reachStatus').value,vote_status:$('voteStatus').value,d2d_status:$('d2dStatus').value,transport_status:$('transportStatus').value,remarks:$('remarks').value,updated_at:new Date().toISOString()};const btn=e.submitter,old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Saving...'}try{const {error}=await sb.from(c.table).update(updates).eq('id',row.id);if(error)throw error;Object.assign(row,updates);render();$('status').textContent='Saved. Page updated.';close()}catch(err){alert(err.message||'Save failed')}finally{if(btn){btn.disabled=false;btn.textContent=old}}}
  function boot(){document.title=config.title+' | Villimale Campaign Manager';$('pageTitle').textContent=config.title;$('pageSubtitle').textContent=config.subtitle;setStatLabels();document.querySelectorAll('[data-party-link]').forEach(a=>{const target=a.dataset.partyLink;a.href=target+'.html?party='+encodeURIComponent(party())});setupStatLinks();['searchInput','statusSelect','houseSelect'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',render));$('clearBtn').onclick=()=>{$('searchInput').value='';$('statusSelect').value=config.defaultFilter||'';$('houseSelect').value='';render()};$('refreshBtn').onclick=()=>load().catch(e=>$('status').textContent=e.message);$('list').addEventListener('click',e=>{const card=e.target.closest('[data-row-id]');if(card){const row=rowById(card.dataset.rowId);if(row)open(row)}});$('closeBtn').onclick=close;$('cancelBtn').onclick=close;$('modal').addEventListener('click',e=>{if(e.target.id==='modal')close()});$('form').addEventListener('submit',save);load().catch(e=>{$('status').textContent=e.message;$('list').innerHTML='<div class="empty">Could not load page.</div>'})}
  document.addEventListener('DOMContentLoaded',boot);
})();
