(()=>{
const page=document.body.dataset.workspacePage;if(!page)return;
const cfg={call:{title:'Call Center',sub:'Call voters and record clear call results only.',field:'phone_status',def:'need-call',opts:[['need-call','Need Call'],['connected','Connected'],['not-answer','Not Receiving Phone'],['disconnected','Disconnected Number'],['switch-off','Switch Off'],['busy','Busy'],['wrong-number','Wrong Number'],['no-phone','No Phone']]},vote:{title:'Vote Result',sub:'Track Will Vote, Not Vote, and Pending voters.',field:'vote_status',def:'pending',opts:[['pending','Pending'],['will-vote','Will Vote'],['no-vote','Not Vote']]},d2d:{title:'Door To Door',sub:'Track visits, follow-up, and pending door-to-door work.',field:'d2d_status',def:'pending',opts:[['pending','Pending'],['visited','Visited'],['follow-up','Follow-up'],['not-home','Not Home']]},transport:{title:'Transportation',sub:'Track transport needs and completion.',field:'transport_status',def:'need-transport',opts:[['none','No Transport'],['need-transport','Need Transport'],['arranged','Arranged'],['completed','Completed']]}}[page];
let rows=[],client=null,selected=null,quick='';const $=id=>document.getElementById(id),clean=v=>String(v||'').trim(),low=v=>clean(v).toLowerCase(),num=v=>new Intl.NumberFormat('en-US').format(v||0),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const party=()=>new URLSearchParams(location.search).get('party')||'PNC';
function sb(){if(client)return client;const c=window.APP_CONFIG;client=window.supabase.createClient(c.supabaseUrl,c.supabaseKey);return client}
function v(r,f){return low(r[f])||(f==='transport_status'?'none':'pending')}
function isAssigned(r){const a=low(r.vote_assigned_by);return a&&a!=='naappe@gmail.com'}
function houses(list){return new Set(list.map(r=>low(r.house||'No house'))).size}
function initials(n){return clean(n).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?'}
function img(r){return r.photo_url?`<img src="${esc(r.photo_url)}" alt="${esc(r.name)}">`:esc(initials(r.name))}
function label(field,value){if(field==='vote_status')return value==='will-vote'?'Will Vote':value==='no-vote'?'Not Vote':'Pending';const f=cfg.opts.find(x=>x[0]===value);return f?f[1]:clean(value)||'Pending'}
async function load(){let out=[],from=0,size=1000;while(true){let q=sb().from(window.APP_CONFIG.table).select('id,image_number,photo_url,name,national_id,house,lives_in,phone,party,election_box,phone_status,reach_status,vote_status,transport_status,d2d_status,remarks,vote_assigned_by').order('image_number').range(from,from+size-1);if(party().toUpperCase()!=='ALL')q=q.eq('party',party());const {data,error}=await q;if(error)throw error;out.push(...(data||[]));if(!data||data.length<size)break;from+=size}rows=out;buildFilters();render()}
function buildFilters(){const st=$('statusSelect'),url=new URLSearchParams(location.search).get('status');st.innerHTML='<option value="">All statuses</option>'+cfg.opts.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');st.value=url||cfg.def;const hs=[...new Set(rows.map(r=>clean(r.house)||'No house'))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));$('houseSelect').innerHTML='<option value="">All houses</option>'+hs.map(h=>`<option value="${esc(low(h))}">${esc(h)}</option>`).join('')}
function filtered(){const s=low($('searchInput').value),st=$('statusSelect').value,h=$('houseSelect').value;return rows.filter(r=>{if(st&&v(r,cfg.field)!==st)return false;if(h&&low(r.house||'No house')!==h)return false;if(quick==='will'&&v(r,'vote_status')!=='will-vote')return false;if(quick==='assigned'&&!isAssigned(r))return false;if(!s)return true;return [r.name,r.national_id,r.house,r.phone,r.party,r.remarks,r.vote_assigned_by].some(x=>low(x).includes(s))})}
function setUrl(){const u=new URL(location.href),st=$('statusSelect').value;if(st)u.searchParams.set('status',st);else u.searchParams.delete('status');history.replaceState(null,'',u)}
function statLabels(){const sp=document.querySelectorAll('.stat span');['Voters','Houses',label(cfg.field,cfg.def),'Will Vote','Assigned'].forEach((t,i)=>{if(sp[i])sp[i].textContent=t})}
function stats(list){$('sTotal').textContent=num(list.length);$('sShowing').textContent=num(houses(list));$('sMain').textContent=num(rows.filter(r=>v(r,cfg.field)===cfg.def).length);$('sWill').textContent=num(rows.filter(r=>v(r,'vote_status')==='will-vote').length);$('sPending').textContent=num(rows.filter(isAssigned).length);$('status').textContent=`Showing ${num(list.length)} voters in ${num(houses(list))} houses. Click a card to update here.`}
function resultBadge(r){const x=v(r,'vote_status');return x==='will-vote'?['will','Will Vote']:x==='no-vote'?['no','Not Vote']:['pending','Pending']}
function group(list){const m=new Map();list.forEach(r=>{const h=clean(r.house)||'No house';if(!m.has(h))m.set(h,[]);m.get(h).push(r)});return[...m.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}))}
function card(r){const b=resultBadge(r);return`<article class="card" data-row-id="${r.id}"><div class="photo">${img(r)}</div><div><div class="name">${esc(r.name||'Unknown voter')}</div><div class="meta">ID: ${esc(r.national_id||'-')}<br>House: ${esc(r.house||'-')}<br>Phone: ${esc(r.phone||'No phone')}<br>Box: ${esc(r.election_box||'-')}</div><div class="badges"><span class="badge ${b[0]}">${b[1]}</span><span class="badge neutral">${esc(label(cfg.field,v(r,cfg.field)))}</span></div><span class="open-note">Click Card / Update</span></div></article>`}
function render(){setUrl();const list=filtered();stats(list);$('list').innerHTML=list.length?group(list).map(([h,a])=>`<div class="house">${esc(h)} · ${num(a.length)} voters</div><div class="grid">${a.map(card).join('')}</div>`).join(''):'<div class="empty">No voters match this filter.</div>';$('list').scrollIntoView({behavior:'smooth',block:'start'})}
function setOptions(id,a){$(id).innerHTML=a.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}
function show(ids){['phoneStatus','reachStatus','voteStatus','d2dStatus','transportStatus'].forEach(id=>{$(id).closest('label').style.display=ids.includes(id)?'grid':'none'})}
function modalSetup(){if(page==='call'){show(['phoneStatus','voteStatus']);$('phoneStatus').closest('label').childNodes[0].textContent='Call Result';setOptions('phoneStatus',cfg.opts);setOptions('voteStatus',[['pending','Pending'],['will-vote','Will Vote'],['no-vote','Not Vote']])}else if(page==='vote')show(['reachStatus','voteStatus']);else if(page==='d2d')show(['reachStatus','voteStatus','d2dStatus']);else show(['voteStatus','transportStatus'])}
function autoReach(){const phone=$('phoneStatus').value,vote=$('voteStatus').value,d2d=$('d2dStatus').value;let reach=$('reachStatus').value;if(page==='call')reach=phone==='connected'?'reached':'not-reached';if(page==='d2d'){if(['visited','follow-up'].includes(d2d))reach='reached';if(['pending','not-home'].includes(d2d)&&vote==='pending')reach='not-reached'}if(['will-vote','no-vote'].includes(vote))reach='reached';$('reachStatus').value=reach;if(page==='call'){const base=$('modalMeta').dataset.base||$('modalMeta').textContent;$('modalMeta').dataset.base=base;$('modalMeta').textContent=base+' · '+(phone==='connected'?'Connected = Reached. Select Vote Status and Save.':'Not connected = Not Reached. Keep vote pending unless known.')}}
function open(r){selected=r.id;$('modalTitle').textContent=r.name||'Update voter';$('modalMeta').textContent=`${r.house||'-'} · ${r.phone||'No phone'}`;$('modalMeta').dataset.base=$('modalMeta').textContent;$('phoneStatus').value=v(r,'phone_status');$('reachStatus').value=v(r,'reach_status')||'not-reached';$('voteStatus').value=v(r,'vote_status');$('d2dStatus').value=v(r,'d2d_status');$('transportStatus').value=v(r,'transport_status');$('remarks').value=r.remarks||'';modalSetup();autoReach();$('modal').hidden=false}
function close(){$('modal').hidden=true;selected=null}
function row(id){return rows.find(r=>String(r.id)===String(id))}
function updates(){autoReach();return{phone_status:$('phoneStatus').value,reach_status:$('reachStatus').value,vote_status:$('voteStatus').value,d2d_status:$('d2dStatus').value,transport_status:$('transportStatus').value,remarks:$('remarks').value,updated_at:new Date().toISOString()}}
async function save(e){e.preventDefault();const r=row(selected);if(!r)return;const data=updates();const btn=e.submitter,old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Saving...'}try{const {error}=await sb().from(window.APP_CONFIG.table).update(data).eq('id',r.id);if(error)throw error;Object.assign(r,data);render();$('status').textContent='Saved. Page updated.';close()}catch(err){alert(err.message||'Save failed')}finally{if(btn){btn.disabled=false;btn.textContent=old}}}
function nav(){document.querySelectorAll('[data-party-link]').forEach(a=>{a.href=a.dataset.partyLink+'.html?party='+encodeURIComponent(party());if(a.dataset.partyLink==='call')a.textContent='Call Center'})}
function statClicks(){const c=document.querySelectorAll('.stat');if(c[0])c[0].onclick=()=>{quick='';$('statusSelect').value='';render()};if(c[1])c[1].onclick=()=>{quick='';$('statusSelect').value='';render()};if(c[2])c[2].onclick=()=>{quick='';$('statusSelect').value=cfg.def;render()};if(c[3])c[3].onclick=()=>{quick='will';$('statusSelect').value='';render()};if(c[4])c[4].onclick=()=>{quick='assigned';$('statusSelect').value='';render()};c.forEach(x=>{x.tabIndex=0;x.title='Filter this page'})}
function boot(){document.title=cfg.title+' | Villimale Campaign Manager';$('pageTitle').textContent=cfg.title;$('pageSubtitle').textContent=cfg.sub;statLabels();nav();statClicks();['searchInput','statusSelect','houseSelect'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',()=>{quick='';render()}));['phoneStatus','voteStatus','d2dStatus','transportStatus'].forEach(id=>$(id).addEventListener('change',autoReach));$('clearBtn').onclick=()=>{quick='';$('searchInput').value='';$('statusSelect').value=cfg.def;$('houseSelect').value='';render()};$('refreshBtn').onclick=()=>load().catch(e=>$('status').textContent=e.message);$('list').onclick=e=>{const c=e.target.closest('[data-row-id]');if(c){const r=row(c.dataset.rowId);if(r)open(r)}};$('closeBtn').onclick=close;$('cancelBtn').onclick=close;$('modal').onclick=e=>{if(e.target.id==='modal')close()};$('form').addEventListener('submit',save);load().catch(e=>{$('status').textContent=e.message;$('list').innerHTML='<div class="empty">Could not load page.</div>'})}
document.addEventListener('DOMContentLoaded',boot);
})();